/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shcoolapp;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import service.service;
import shcoolapp.model.Ocena;
import shcoolapp.model.Predmet;
import shcoolapp.model.Ucenik;

/**
 *
 * @author demir
 */
public class Ocene extends javax.swing.JFrame {
    
    private int UcenikId;
    private Ucenik ucenk;
    private List<Predmet> predmets;
    List<Ocena> predmeti;

    public List<Ocena> getPredmeti() {
        return predmeti;
    }

    public void setPredmeti(List<Ocena> predmeti) {
        this.predmeti = predmeti;
    }
            
    public List<Predmet> getPredmets() {
        return predmets;
    }

    public void setPredmets(List<Predmet> predmets) {
        this.predmets = predmets;
    }
            
    public Ucenik getUcenk() {
        return ucenk;
    }

    public void setUcenk(Ucenik ucenk) {
        this.ucenk = ucenk;
    }
    
    
    public int getUcenikId() {
        return UcenikId;
    }

    public void setUcenikId(int UcenikId) {
        this.UcenikId = UcenikId;
    }
    
    public Ocene(int UcenikId) throws SQLException {
        service s = new service(); 
        
        this.UcenikId = UcenikId;
        setUcenk(s.getUcenik(this.UcenikId));
        
        initComponents(); 
        this.setLocationRelativeTo(null);
        jLabel6.setText(this.ucenk.Ime+" "+this.ucenk.Prezime);
        try {
            SetPredmeti();
        } catch (SQLException ex) {
            Logger.getLogger(Ocene.class.getName()).log(Level.SEVERE, null, ex);
        }
        GetOcene();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextField1.setToolTipText("");

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jButton1.setText("Oceni");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField1))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel6)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        service s = new service();
        List<Ocena> ocene = new ArrayList<Ocena>();
        
        if (jTextField1.getText() != "") {
            Ocena ocena1 = new Ocena(Integer.parseInt(jTextField1.getText()),  predmets.get(0).Id, getUcenikId());
            ocene.add(ocena1);
        }
        
        if (jTextField1.getText() != "") {
            Ocena ocena2 = new Ocena(Integer.parseInt(jTextField2.getText()),  predmets.get(1).Id, getUcenikId());
            ocene.add(ocena2);
        }
        
        if (jTextField1.getText() != "") {
            Ocena ocena3 = new Ocena(Integer.parseInt(jTextField3.getText()),  predmets.get(2).Id, getUcenikId());
            ocene.add(ocena3);
        }
        
        if (jTextField1.getText() != "") {
            Ocena ocena4 = new Ocena(Integer.parseInt(jTextField4.getText()),  predmets.get(3).Id, getUcenikId());
            ocene.add(ocena4);
        }
        
        if (jTextField1.getText() != "") {
            Ocena ocena5 = new Ocena(Integer.parseInt(jTextField5.getText()),  predmets.get(4).Id, getUcenikId());
            ocene.add(ocena5);
        }
        
        try {
            if (ocene.size() > 0) {
                s.InsertOcene(ocene);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ocene.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ocene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ocene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ocene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ocene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Ocene(0).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Ocene.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void SetPredmeti() throws SQLException {
        service s = new service();
        List<Predmet> predmeti = s.getPredmeti();
        setPredmets(predmeti);
        
        jLabel1.setText(predmeti.get(0).getPredmet());
        jLabel7.setText(String.valueOf(predmeti.get(0).getId()));
        jLabel7.setForeground(new Color(250,251,252));
                
        jLabel2.setText(predmeti.get(1).getPredmet());
        jLabel8.setText(String.valueOf(predmeti.get(1).getId()));
        jLabel8.setForeground(new Color(250,251,252));
        
        jLabel3.setText(predmeti.get(2).getPredmet());
        jLabel9.setText(String.valueOf(predmeti.get(2).getId()));
        jLabel9.setForeground(new Color(250,251,252));
        
        jLabel4.setText(predmeti.get(3).getPredmet());
        jLabel10.setText(String.valueOf(predmeti.get(3).getId())); 
        jLabel10.setForeground(new Color(250,251,252));
        
        jLabel5.setText(predmeti.get(4).getPredmet());
        jLabel11.setText(String.valueOf(predmeti.get(4).getId()));
        jLabel11.setForeground(new Color(250,251,252));
    }
    
    public void GetOcene() throws SQLException {
        service s = new service();
        List<Ocena> predmeti = s.GetOcene(getUcenikId());
        setPredmeti(predmeti);
       
        for (int i = 0; i< predmeti.size(); i++) {            
            
            if (jLabel7.getText().equals(String.valueOf(predmeti.get(i).getPredmetId()))) {
                jTextField1.setText(String.valueOf(predmeti.get(i).Ocena));
            }
            
            if (jLabel8.getText().equals(String.valueOf(predmeti.get(i).getPredmetId()))) {
                jTextField2.setText(String.valueOf(predmeti.get(i).Ocena));
            }
            
            if (jLabel9.getText().equals(String.valueOf(predmeti.get(i).getPredmetId()))) {
                jTextField3.setText(String.valueOf(predmeti.get(i).Ocena));
            }
            
            if (jLabel10.getText().equals(String.valueOf(predmeti.get(i).getPredmetId()))) {
                jTextField4.setText(String.valueOf(predmeti.get(i).Ocena));
            }
            
            if (jLabel11.getText().equals(String.valueOf(predmeti.get(i).getPredmetId()))) {
                jTextField5.setText(String.valueOf(predmeti.get(i).Ocena));
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    private String toString(int id) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
